[package]
name = "view3d"
version = "0.1.0"
authors = ["Jon Ayerdi <jon_ayerdi_33@hotmail.es>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
minifb = "0.11.2"
